### PR TITLE
[WIP] Faster test matrix

### PR DESCRIPTION
**Pull request by thecrypticace**
Before:
| OS | Node  | Time |
| :-- | -- | --: |
| Ubuntu | 12.21 | 4:29 | 
| Windows | 12.21 | 8:01 | 
| Ubuntu | 13.14 | 4:34 | 
| Windows | 13.14 | 8:31 | 
| Ubuntu | 14.16 | 4:47 | 
| Windows | 14.16 | 8:54 | 
| **Total** |  | **39:16** | 

After — when dependencies change:
| OS | Node  | Time |
| :-- | -- | --: |
| Ubuntu  | 12.21 | 4:18 |
| Windows | 12.21 | 7:49 |
| Ubuntu  | 15.12 | 4:47 |
| Windows | 15.12 | 7:58 |
| **Total** |  | **24:52** | 

After — when dependencies are cached:
| OS | Node  | Time |
| :-- | -- | --: |
| Ubuntu  | 12.21 | 2:43 |
| Windows | 12.21 | 6:01 |
| Ubuntu  | 15.12 | 3:19 |
| Windows | 15.12 | 4:55 |
| **Total** |  | **16:58** |

### CODE REVIEW

**Comment by ankurk91** [comment]
What about `npm ci`
https://docs.npmjs.com/cli/v6/commands/npm-ci

**Comment by thecrypticace** [comment]
`npm ci` stands for `npm clean install`. I floated the idea of using it except we can't cache `node_modules` when using it. It deletes any existing `node_modules` before running. We *don't* want this.

Now, we could cache the content of the npm cache itself. I might look into that. Not sure how well that will play with how playwright downloads browsers for integration testing though.

**Comment by thecrypticace** [comment]
@JeffreyWay I'm thinking about landing the reduced testing matrix change separately so we only have 4 builds instead of 6. I want to fiddle around with the caching some more before we _maybe_ land this change. You cool with that?

**Comment by JeffreyWay** [comment]
Yep, works for me. 👍

**Comment by thecrypticace** [comment]
Closing for now. I may re-open this in the future if we switch to something like pnpm. The reduced test matrix we have is sufficient.

**Pull request closed without merging**
