### PR TITLE
Update autoprefixer.md

### PR DESCRIPTION
**Pull request by ethanclevenger91**
I couldn't get autoprefixer to config properly with the documented method. Did this instead, worked. Can't vouch for whether or not the existing documentation works as advertised for postCss directly so I left it intact.

### CODE REVIEW

**Comment by thecrypticace** [comment]
If `{ autoprefixer: false }` isn't working we should definitely figure out how to fix that instead because that should work.

**Comment by ethanclevenger91** [comment]
I was actually trying to tweak autoprefixer options. I suppose it's possible that disabling it entirely is simpler than setting options?

```
.sass('app.scss', 'dist')
    .options({
        postCss: [
            require('autoprefixer')({
                grid: true,
            })
        ]
    })
```

**Comment by ethanclevenger91** [comment]
@thecrypticace I guess my issue could have actually been [this](https://github.com/JeffreyWay/laravel-mix/issues/2340#issue-577126665)

**Comment by thecrypticace** [comment]
I've verified that, at least in the latest version of Mix, this is not an issue and the autoprefixer config works as expected when using postcss or a preprocessor like sass/scss

**Pull request closed without merging**
